# Generated by Django 4.2.6 on 2023-10-16 11:03

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Project",
            fields=[
                (
                    "projectId",
                    models.CharField(max_length=20, primary_key=True, serialize=False),
                ),
                ("name", models.CharField(max_length=150)),
                ("description", models.TextField()),
                (
                    "year",
                    models.IntegerField(
                        validators=[
                            django.core.validators.MinValueValidator(1900),
                            django.core.validators.MaxValueValidator(2023),
                        ]
                    ),
                ),
                ("mentor", models.CharField(max_length=100)),
                ("youtubeLink", models.URLField(default="")),
                ("category", models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name="teamDetails",
            fields=[
                (
                    "roll",
                    models.CharField(max_length=20, primary_key=True, serialize=False),
                ),
                ("name", models.CharField(max_length=100)),
                ("projectId", models.CharField(max_length=20)),
            ],
        ),
    ]
