# Generated by Django 4.2.6 on 2023-10-19 03:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("data", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="project",
            name="img",
            field=models.CharField(default="N N N N N", max_length=20),
        ),
    ]
